### ISSUE TITLE
detect monitors

### ISSUE THREAD

**Issue by b08x** [syncopatedlinux/ansible#31]
accommodate multi-monitor installs

```yaml

- name: get outputs
  shell: | 
     outputs=$(xrandr --query | grep " connected" | cut -d" " -f1)
  become_user: {{ user.name }}
 register: monitors
```

then in jinja template

if monitors include (2)
 set workspaces according
if less than 2 (or 1)
 set workspaces according
end
